using System;
using System.Collections.Generic;
using System.Linq;

namespace Clr2Ts.Transpiler.Transpilation
{
    /// <summary>
    /// Represents the result of a transpilation process.
    /// </summary>
    public sealed class TranspilationResult
    {
        /// <summary>
        /// Creates a <see cref="TranspilationResult"/>.
        /// </summary>
        /// <param name="codeFragments">Code fragments that were generated by the transpilation process.</param>
        /// <exception cref="ArgumentNullException">Thrown when <paramref name="codeFragments"/> is null.</exception>
        public TranspilationResult(IEnumerable<CodeFragment> codeFragments)
        {
            if (codeFragments == null) throw new ArgumentNullException(nameof(codeFragments));

            CodeFragments = codeFragments.ToList();
        }

        /// <summary>
        /// Gets the code fragments that were generated by the transpilation process.
        /// </summary>
        public IEnumerable<CodeFragment> CodeFragments { get; }

        /// <summary>
        /// Creates a <see cref="TranspilationResult"/> that adds new code fragments to this result.
        /// </summary>
        /// <param name="codeFragments">New code fragments that should be added.</param>
        /// <returns>A <see cref="TranspilationResult"/> that adds new code fragments to this result.</returns>
        public TranspilationResult AddCodeFragments(IEnumerable<CodeFragment> codeFragments)
        {
            if (codeFragments == null) throw new ArgumentNullException(nameof(codeFragments));

            return new TranspilationResult(CodeFragments.Concat(codeFragments));
        }

        /// <summary>
        /// Gets all dependencies of the code fragments that are
        /// not resolved by code fragments in this result itself.
        /// </summary>
        /// <returns>A sequence with the unresolved dependencies.</returns>
        public IEnumerable<CodeFragmentId> GetUnresolvedDependencies()
        {
            var resolvable = new HashSet<CodeFragmentId>(CodeFragments.Select(x => x.Id));

            return CodeFragments
                .SelectMany(x => x.Dependencies)
                .Where(x => !resolvable.Contains(x));
        }
    }
}